########################################################################
################### CommandVoter Configuration File ####################
######### Use %v to get the number of times a player has voted #########
#################### Use %p to get the players name ####################
######## Use &- then the Colour code, to be able to use colours ########
###### ~Other messages are for a player who performs the command #######
######### for another player (OP's) or a player with permission ########
########################################################################

enable-metrics: true

messages:
  playerNotOnline: '&4%p is not online!'
  permission: '&4You do not have permission to perform this command!'
  noRewards: '&4You need to vote more before you can be rewarded!'
  noRewardsOther: '&4%p is not allowed a reward yet!'
  alreadyRewarded: '&5You have already been rewarded for your current vote!'
  alreadyRewardedOther: '&5%p has already been rewarded!'
  rewardMessage: '&2You have been rewarded for Voting!'
  rewardMessageSender: '&2%p has been rewared!'
  notEnoughSpace: '&4There is not enough space in your inventory to be able to claim your rewards!'
  notEnoughSpaceOther: '&4There is not enough space in %p''s inventory!'

playerJoinMessage: '&2%p has voted &5%v &2times!'
playerTopVoterMessage: '&2%p has voted &5%v &2times!'
playerBroadcastMessage: '&2%p has just voted for us!'
listTopVoters: 5

votelinks:
  - '&2%p you can vote for use by clicking the link!'
  - '&6Click the link to vote (&4http://vote-link.com&6)'
  - '&7Another vote link'
  - '&2%p, you have voted &5%v times'

rewards:
  '1':
    - '384:12'
  '3':
    - '264:1'
    - '266:9'
  '5':
    - '57:1'
  '10':
    - '57:5'
    - '310:1'
    - '311:1'
    - '312:1'
    - '313:1'

players: []
