name: CommandVoter
main: Me.MrEditor97.CommandVoter.CommandVoter
version: 0.0.7
depends: [Votifier]
commands:
  vote:
    description: Voting link
    usage: /vote
    permission: commandvoter.vote
    permission-message: You don't have permission to use this command
  topvoters:
    description: Top Voters List command
    usage: /topvoters
    permission: commandvoter.topvoters
    permission-message: You don't have permission to use this command
  rewards:
    description: Player rewards for voting
    usage: /rewards
    permission: commandvoter.rewards
    permission-message: You don't have permission to use this command

permissions:
  commandvoter.*:
    description: Gives access to all commands
    children:
      commandvoter.vote: true
      commandvoter.topvoters: true
      commandvoter.rewards: true
      commandvoter.rewards.others: true
  commandvoter.vote:
    description: Allows permission to the /vote command
    default: true
  commandvoter.topvoters:
    description: Allows permission to the /topvoters command
    default: op
  commandvoter.rewards:
    description: Allows permission to the /reward command (Only for the player who performed the command)
    default: false
  commandvoter.rewards.others:
    description: Allows permission to the /reward command (All players)
    default: op
    children:
      commandvoter.rewards: true